### PR TITLE
Initialize vscode extension

### PR DESCRIPTION
**Pull request by rclsilver**

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report package-vscode#2.0 ✘  
* Stage 1
  * Package ✘

**Comment by ovh-cds** [comment]
CDS Report package-vscode#3.0 ✘  
* Stage 1
  * Package ✘

**Comment by ovh-cds** [comment]
CDS Report package-vscode#4.0 ✘  
* Stage 1
  * Package ✘

**Comment by ovh-cds** [comment]
CDS Report package-vscode#5.0 ✘  
* Stage 1
  * Package ✘

**Comment by ovh-cds** [comment]
CDS Report package-vscode#6.0 ✘  
* Stage 1
  * Package ✘

**Comment by ovh-cds** [comment]
CDS Report package-vscode#7.0 ✘  
* Stage 1
  * Package ✘

**Comment by ovh-cds** [comment]
CDS Report package-vscode#8.0 ✘  
* Stage 1
  * Package ✘

**Comment by ovh-cds** [comment]
CDS Report package-vscode#9.0 ✘  
* Stage 1
  * Package ✘

**Comment by ovh-cds** [comment]
CDS Report package-vscode#14.0 ✘  
* Stage 1
  * Package ✘

**Comment by ovh-cds** [comment]
CDS Report package-vscode#15.0 ✘  
* Stage 1
  * Package ✘

**Review by Inozuma — APPROVED** [review]

**Comment by ovh-cds** [comment]
CDS Report package-vscode#16.0 ■   
* Stage 1
  * Package ■

**Comment by ovh-cds** [comment]
CDS Report package-vscode#17.0 ■   
* Stage 1
  * Package ■

**Comment by ovh-cds** [comment]
CDS Report package-vscode#17.0 ■   
* Stage 1
  * Package ■

**Review by Inozuma — APPROVED** [review]

**Pull request merged**
