### PR TITLE
(feat): Add a custom label for delayed tasks

### PR DESCRIPTION
**Pull request by floriancazals**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Display improvement.

* **What is the current behavior?** (You can also link to an open issue here)
Delayed tasks appear with the TODO state.

* **What is the new behavior (if this is a feature change)?**
Delayed tasks appear with the DELAYED new state.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
NA.

* **Other information**:
NA

### CODE REVIEW

**Comment by rclsilver** [comment]
Instead of "custom label", I guess you should tell "new state". Label is nothing in uTask and custom state is for template authors

**Comment by floriancazals** [comment]
> Instead of "custom label", I guess you should tell "new state". Label is nothing in uTask and custom state is for template authors

Ack, PR updated

**Comment by ovh-cds** [comment]
CDS Report test#1617.0 ✘  
* tests and lint
  * golangci-lint ✔ 
  * unit-test and integration-tests ✘

**Review by wI2L — APPROVED** [review]
LGTM

**Pull request merged**
