### PR TITLE
chore(dep): migrating µTask build to Go 1.18

### PR DESCRIPTION
**Pull request by rbeuque74**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Chore

* **What is the current behavior?** (You can also link to an open issue here)
Build using Go 1.17

* **What is the new behavior (if this is a feature change)?**
Build using Go 1.18

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Other information**:

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report test#1363.0 ✘  
* tests and lint
  * golangci-lint ✘  
  * unit-test and integration-tests ✘

**Comment by ovh-cds** [comment]
CDS Report test#1366.0 ✘  
* tests and lint
  * golangci-lint ✘  
  * unit-test and integration-tests ✘

**Comment by ovh-cds** [comment]
CDS Report test#1380.0 ✘  
* tests and lint
  * golangci-lint ✔ 
  * unit-test and integration-tests ✘

**Comment by ovh-cds** [comment]
CDS Report test#1381.0 ✘  
* tests and lint
  * golangci-lint ✔ 
  * unit-test and integration-tests ✘

**Comment by ovh-cds** [comment]
CDS Report test#1383.0 ✘  
* tests and lint
  * golangci-lint ✔ 
  * unit-test and integration-tests ✘

**Comment by ovh-cds** [comment]
CDS Report test#1385.0 ■   
* tests and lint
  * golangci-lint ✔ 
  * unit-test and integration-tests ■

**Comment by ovh-cds** [comment]
CDS Report test#1385.0 ■   
* tests and lint
  * golangci-lint ✔ 
  * unit-test and integration-tests ■

**Review by rclsilver — APPROVED** [review]

**Pull request merged**
